version: "3"

services:
  viadot_2_azure:
    image: ghcr.io/dyvenia/viadot/viadot-azure:0.2
    container_name: viadot_2_azure
    volumes:
      # - ${HOME}/.databricks-connect:/home/viadot/.databricks-connect
      # - ${HOME}/.config/viadot/config.yaml:/home/viadot/.config/viadot/config.yaml
      - ../:/home/viadot
    shm_size: "4gb"
    command: sleep infinity
    restart: "unless-stopped"
